Errors at compile time with NS >= 3.17:
  ../src/plc/model/plc-net-device.cc: In member function ‘virtual void ns3::PLC_NetDevice::DoStart()’:
  ../src/plc/model/plc-net-device.cc:87:2: error: ‘DoStart’ is not a member of ‘ns3::NetDevice’
    NetDevice::DoStart ();
    ^
  ../src/plc/model/plc-net-device.cc: In member function ‘void ns3::PLC_NetDevice::LinkUp()’:
  ../src/plc/model/plc-net-device.cc:220:13: error: ‘class ns3::PLC_Phy’ has no member named ‘Start’
     GetPhy()->Start();

Solution found:

  Use DoInitialize() instead of DoStart() and Initialize() instead of Start().
  See http://code.nsnam.org/ns-3.17/raw-file/96ada8e6b920/CHANGES.html