Errors at compile time with NS >= 3.16:
  /usr/include/boost/graph/dijkstra_shortest_paths.hpp:165:53: error: no matching function for call to ‘get(double*&, long unsigned int)’
           D source_dist = get(m_distance, source(e, g));

  /usr/include/boost/graph/dijkstra_shortest_paths.hpp:165:53: note:   mismatched types ‘boost::detail::underlying_edge_desc_map_type<E>’ and ‘double*’
           D source_dist = get(m_distance, source(e, g));

Solution found:

  Return to the commit 4228940c3af3e89f665134d78718c02f4e65e587. This modification was revoked in bcaae643e7ff781289e40436b54511a6abf43f04 with the parallel channel calculation added. I don't really know if this line is a problem with the paralell calculation but it's the only solution I've found to compile. All tests and examples provided work well.