Errors at compile time with NS >= 3.17 (Waf >= 1.6):
    File "/home/ju/doctorat/ns3/ns-allinone-3.17/ns-3.17/src/plc/wscript", line 85, in build
      bld.add_subdirs('examples')
  AttributeError: 'BuildContext' object has no attribute 'add_subdirs'

Solution found:

  Use recurse() instead of add_subdirs().
  See https://ftp.samba.org/pub/unpacked/waf/docs/book/intro_waf_1.6.txt